-- MySQL Script generated by MySQL Workbench
-- Sat Nov 22 14:24:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica` DEFAULT CHARACTER SET utf8 ;
USE `clinica` ;

-- -----------------------------------------------------
-- Table `clinica`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`pacientes` (
  `id_pacientes` INT NOT NULL AUTO_INCREMENT,
  `nome_pacientes` VARCHAR(100) NOT NULL,
  `cpf_pacientes` VARCHAR(45) NULL,
  `numero_pacientes` VARCHAR(45) NULL,
  `email_pacientes` VARCHAR(100) NULL,
  PRIMARY KEY (`id_pacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica`.`medicos` (
  `id_medico` INT NOT NULL AUTO_INCREMENT,
  `nome_medicos` VARCHAR(100) NOT NULL,
  `email_medicios` VARCHAR(100) NULL,
  `telefone_medicos` VARCHAR(45) NULL,
  `pacientes_id_pacientes` INT NOT NULL,
  PRIMARY KEY (`id_medico`, `pacientes_id_pacientes`),
  INDEX `fk_medicos_pacientes_idx` (`pacientes_id_pacientes` ASC) ,
  CONSTRAINT `fk_medicos_pacientes`
    FOREIGN KEY (`pacientes_id_pacientes`)
    REFERENCES `clinica`.`pacientes` (`id_pacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
